In [3]:
import pandas as pd
df = pd.read_csv('../data/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.shape
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [6]:
bad = pd.to_numeric(df['TotalCharges'],errors='coerce').isna()
bad.sum()
df[bad]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [18]:
df["tenure"].describe()

count    7043.000000
mean       32.371149
std        24.559481
min         0.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: tenure, dtype: float64

In [19]:
df[bad]['tenure']

488     0
753     0
936     0
1082    0
1340    0
3331    0
3826    0
4380    0
5218    0
6670    0
6754    0
Name: tenure, dtype: int64

In [10]:
df['Churn'].value_counts(normalize=True)

Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

In [12]:
df.groupby('Contract')['Churn'].value_counts(normalize=True)

Contract        Churn
Month-to-month  No       0.572903
                Yes      0.427097
One year        No       0.887305
                Yes      0.112695
Two year        No       0.971681
                Yes      0.028319
Name: proportion, dtype: float64

In [13]:
df.groupby("Contract")["Churn"].value_counts(normalize=True).unstack()["Yes"].sort_values(ascending=False)

Contract
Month-to-month    0.427097
One year          0.112695
Two year          0.028319
Name: Yes, dtype: float64

In [15]:
def churn_rate(col):
    return df.groupby(col)["Churn"].value_counts(normalize=True).unstack()["Yes"].sort_values(ascending=False)

for col in ["InternetService", "PaymentMethod", "TechSupport", "OnlineSecurity", "Dependents", "Partner", "SeniorCitizen", "PaperlessBilling", "gender"]:
    print(churn_rate(col), "\n")

InternetService
Fiber optic    0.418928
DSL            0.189591
No             0.074050
Name: Yes, dtype: float64

PaymentMethod
Electronic check             0.452854
Mailed check                 0.191067
Bank transfer (automatic)    0.167098
Credit card (automatic)      0.152431
Name: Yes, dtype: float64

TechSupport
No                     0.416355
Yes                    0.151663
No internet service    0.074050
Name: Yes, dtype: float64

OnlineSecurity
No                     0.417667
Yes                    0.146112
No internet service    0.074050
Name: Yes, dtype: float64

Dependents
No     0.312791
Yes    0.154502
Name: Yes, dtype: float64

Partner
No     0.329580
Yes    0.196649
Name: Yes, dtype: float64

SeniorCitizen
1    0.416813
0    0.236062
Name: Yes, dtype: float64

PaperlessBilling
Yes    0.335651
No     0.163301
Name: Yes, dtype: float64

gender
Female    0.269209
Male      0.261603
Name: Yes, dtype: float64

In [20]:
pd.cut(df["tenure"], bins=[0, 6, 12, 24, 48, 100]).isna().sum()

11

In [16]:
bands = pd.cut(df["tenure"], bins=[-1, 6, 12, 24, 48, 100],
               labels=["0-6", "7-12", "13-24", "25-48", "49+"])
df.groupby(bands, observed=True)["Churn"].value_counts(normalize=True).unstack()["Yes"]

tenure
0-6      0.529372
7-12     0.358865
13-24    0.287109
25-48    0.203890
49+      0.095132
Name: Yes, dtype: float64

In [21]:
bands = pd.cut(df["tenure"], bins=[-1, 6, 12, 24, 48, 100],
               labels=["0-6", "7-12", "13-24", "25-48", "49+"])
df.groupby(bands, observed=True)["Churn"].value_counts(normalize=True).unstack()["Yes"]

tenure
0-6      0.529372
7-12     0.358865
13-24    0.287109
25-48    0.203890
49+      0.095132
Name: Yes, dtype: float64

In [22]:
df["tenure"].describe()

count    7043.000000
mean       32.371149
std        24.559481
min         0.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: tenure, dtype: float64

In [23]:
df["MonthlyCharges"].describe()

count    7043.000000
mean       64.761692
std        30.090047
min        18.250000
25%        35.500000
50%        70.350000
75%        89.850000
max       118.750000
Name: MonthlyCharges, dtype: float64

In [24]:
charge_bands = pd.cut(df["MonthlyCharges"], bins=[0, 35, 60, 85, 200],
                      labels=["<35", "35-60", "60-85", "85+"])
df.groupby(charge_bands, observed=True)["Churn"].value_counts(normalize=True).unstack()["Yes"]

MonthlyCharges
<35      0.108934
35-60    0.254438
60-85    0.329892
85+      0.338208
Name: Yes, dtype: float64

In [25]:
for col in ["OnlineBackup", "DeviceProtection", "StreamingTV", "StreamingMovies", "MultipleLines", "PhoneService"]:
    print(churn_rate(col), "\n")

OnlineBackup
No                     0.399288
Yes                    0.215315
No internet service    0.074050
Name: Yes, dtype: float64

DeviceProtection
No                     0.391276
Yes                    0.225021
No internet service    0.074050
Name: Yes, dtype: float64

StreamingTV
No                     0.335231
Yes                    0.300702
No internet service    0.074050
Name: Yes, dtype: float64

StreamingMovies
No                     0.336804
Yes                    0.299414
No internet service    0.074050
Name: Yes, dtype: float64

MultipleLines
Yes                 0.286099
No                  0.250442
No phone service    0.249267
Name: Yes, dtype: float64

PhoneService
Yes    0.267096
No     0.249267
Name: Yes, dtype: float64